import { Feather } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import React from 'react';
import { ActivityIndicator, Alert, DimensionValue, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { checklist } from '@/data/compliance'; import { useApp } from '@/context/AppContext'; import { useColors } from '@/hooks/useColors'; import { Card, InstitutionPicker, Pill, Screen } from '@/components/AppUI';
export default function Rounds(){const c=useColors();const {statuses,setStatus,resetRound,ready}=useApp();const done=checklist.filter(x=>statuses[x.id]==='complete').length;const flagged=checklist.filter(x=>statuses[x.id]==='flagged').length;const pct=Math.round(done/checklist.length*100);
 if(!ready)return <Screen title="Inspection rounds" eyebrow="CMS COMPLIANCE"><ActivityIndicator style={{marginTop:60}} color={c.primary}/></Screen>;
 const progressWidth=(pct+'%') as DimensionValue; return <Screen title="Inspection rounds" eyebrow="CMS COMPLIANCE" right={<Pressable testID="reset-round" onPress={()=>Alert.alert('Start a new round?','This clears all completed and flagged items.',[{text:'Cancel',style:'cancel'},{text:'Reset',style:'destructive',onPress:resetRound}])}><Feather name="rotate-ccw" size={21} color={c.primaryForeground}/></Pressable>}><ScrollView contentContainerStyle={s.content}><InstitutionPicker/><Card><View style={s.progressTop}><View><Text style={[s.big,{color:c.foreground}]}>{pct}%</Text><Text style={[s.sub,{color:c.mutedForeground}]}>{done} of {checklist.length} checks complete</Text></View><Pill icon="flag" label={flagged+' flagged'} tone={flagged?'amber':'teal'}/></View><View style={[s.track,{backgroundColor:c.muted}]}><View style={[s.fill,{backgroundColor:c.accent,width:progressWidth}]}/></View></Card><Text style={[s.section,{color:c.foreground}]}>Walk-through checklist</Text>{checklist.map(item=>{const state=statuses[item.id]??'open';return <Card key={item.id}><View style={s.itemTop}><View style={{flex:1}}><Text style={[s.category,{color:c.primary}]}>{item.category.toUpperCase()}</Text><Text style={[s.itemTitle,{color:c.foreground}]}>{item.title}</Text><Text style={[s.detail,{color:c.mutedForeground}]}>{item.detail}</Text></View></View><View style={s.actions}><Pressable testID={'flag-'+item.id} onPress={()=>{setStatus(item.id,state==='flagged'?'open':'flagged');void Haptics.selectionAsync()}} style={[s.action,{borderColor:state==='flagged'?c.accent:c.border,backgroundColor:state==='flagged'?c.accentSoft:c.card}]}><Feather name="flag" size={16} color={state==='flagged'?c.accent:c.mutedForeground}/><Text style={[s.actionText,{color:state==='flagged'?c.accentForeground:c.mutedForeground}]}>Flag</Text></Pressable><Pressable testID={'complete-'+item.id} onPress={()=>{setStatus(item.id,state==='complete'?'open':'complete');void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)}} style={[s.action,s.complete,{borderColor:state==='complete'?c.success:c.primary,backgroundColor:state==='complete'?c.successSoft:c.primarySoft}]}><Feather name={state==='complete'?'check-circle':'circle'} size={17} color={state==='complete'?c.success:c.primary}/><Text style={[s.actionText,{color:state==='complete'?c.success:c.primary}]}>{state==='complete'?'Complete':'Mark complete'}</Text></Pressable></View></Card>})}</ScrollView></Screen>}
const s=StyleSheet.create({content:{paddingBottom:120,gap:12},progressTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},big:{fontFamily:'Inter_700Bold',fontSize:30},sub:{fontFamily:'Inter_400Regular',fontSize:12,marginTop:2},track:{height:7,borderRadius:99,overflow:'hidden',marginTop:14},fill:{height:'100%',borderRadius:99},section:{fontFamily:'Inter_700Bold',fontSize:18,marginHorizontal:17,marginTop:7},category:{fontFamily:'Inter_700Bold',fontSize:9,letterSpacing:1.1},itemTop:{flexDirection:'row'},itemTitle:{fontFamily:'Inter_600SemiBold',fontSize:15,lineHeight:20,marginTop:4},detail:{fontFamily:'Inter_400Regular',fontSize:13,lineHeight:19,marginTop:5},actions:{flexDirection:'row',gap:8,marginTop:14},action:{height:38,paddingHorizontal:12,borderWidth:1,borderRadius:9,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},complete:{flex:1},actionText:{fontFamily:'Inter_600SemiBold',fontSize:12}});
