import { Feather } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import React, { ReactNode, useState } from 'react';
import { Modal, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { institutions } from '@/data/compliance';
import { useApp } from '@/context/AppContext';

export function Screen({children,title,eyebrow,right}:{children:ReactNode;title:string;eyebrow:string;right?:ReactNode}){
 const c=useColors(); const i=useSafeAreaInsets();
 return <View style={[s.screen,{backgroundColor:c.background}]}><View style={[s.header,{paddingTop:Platform.OS==='web'?67:i.top+12,backgroundColor:c.primary}]}><View style={{flex:1}}><Text style={s.eyebrow}>{eyebrow}</Text><Text style={s.title}>{title}</Text></View>{right}</View>{children}</View>
}
export function InstitutionPicker(){
 const c=useColors(); const {institutionId,setInstitutionId}=useApp(); const [open,setOpen]=useState(false); const current=institutions.find(x=>x.id===institutionId) ?? institutions[0];
 return <><Pressable testID="institution-picker" onPress={()=>setOpen(true)} style={({pressed})=>[s.picker,{backgroundColor:c.card,borderColor:c.border,opacity:pressed?.75:1}]}><View style={[s.iconBox,{backgroundColor:c.primarySoft}]}><Feather name="map-pin" size={17} color={c.primary}/></View><View style={{flex:1}}><Text style={[s.pickerLabel,{color:c.mutedForeground}]}>FACILITY TYPE</Text><Text numberOfLines={1} style={[s.pickerText,{color:c.foreground}]}>{current.name}</Text></View><Feather name="chevron-down" size={20} color={c.mutedForeground}/></Pressable>
 <Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setOpen(false)}><View style={[s.modal,{backgroundColor:c.background}]}><View style={[s.modalHeader,{borderBottomColor:c.border}]}><View><Text style={[s.modalTitle,{color:c.foreground}]}>Facility type</Text><Text style={[s.modalSub,{color:c.mutedForeground}]}>Tailor your rounds and references</Text></View><Pressable onPress={()=>setOpen(false)} testID="close-institution-picker"><Feather name="x" size={26} color={c.foreground}/></Pressable></View><ScrollView contentContainerStyle={s.modalList}>{institutions.map(item=><Pressable key={item.id} testID={'institution-'+item.id} onPress={()=>{setInstitutionId(item.id);void Haptics.selectionAsync();setOpen(false)}} style={[s.option,{backgroundColor:item.id===institutionId?c.primarySoft:c.card,borderColor:item.id===institutionId?c.primary:c.border}]}><View style={{flex:1}}><Text style={[s.optionTitle,{color:c.foreground}]}>{item.name}</Text><Text style={[s.optionSub,{color:c.mutedForeground}]}>{item.ecfr}</Text></View>{item.id===institutionId&&<Feather name="check-circle" size={21} color={c.primary}/>}</Pressable>)}</ScrollView></View></Modal></>
}
export function Pill({icon,label,tone='teal'}:{icon:keyof typeof Feather.glyphMap;label:string;tone?:'teal'|'amber'|'green'}){const c=useColors();const bg=tone==='amber'?c.accentSoft:tone==='green'?c.successSoft:c.primarySoft;const fg=tone==='amber'?c.accentForeground:tone==='green'?c.success:c.primary;return <View style={[s.pill,{backgroundColor:bg}]}><Feather name={icon} size={13} color={fg}/><Text style={[s.pillText,{color:fg}]}>{label}</Text></View>}
export function Card({children}:{children:ReactNode}){const c=useColors();return <View style={[s.card,{backgroundColor:c.card,borderColor:c.border}]}>{children}</View>}
const s=StyleSheet.create({screen:{flex:1},header:{paddingHorizontal:20,paddingBottom:18,flexDirection:'row',alignItems:'flex-end',gap:12},eyebrow:{fontFamily:'Inter_700Bold',fontSize:11,letterSpacing:1.5,color:'#FCD34D',marginBottom:5},title:{fontFamily:'Inter_700Bold',fontSize:26,color:'#FFFFFF'},picker:{marginHorizontal:16,marginTop:16,borderWidth:1,borderRadius:12,padding:12,flexDirection:'row',alignItems:'center',gap:10},iconBox:{height:36,width:36,borderRadius:8,alignItems:'center',justifyContent:'center'},pickerLabel:{fontFamily:'Inter_700Bold',fontSize:9,letterSpacing:1.2},pickerText:{fontFamily:'Inter_600SemiBold',fontSize:14,marginTop:2},modal:{flex:1},modalHeader:{paddingTop:24,paddingHorizontal:20,paddingBottom:16,borderBottomWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},modalTitle:{fontFamily:'Inter_700Bold',fontSize:24},modalSub:{fontFamily:'Inter_400Regular',fontSize:13,marginTop:3},modalList:{padding:16,gap:9,paddingBottom:40},option:{padding:14,borderRadius:12,borderWidth:1,flexDirection:'row',alignItems:'center'},optionTitle:{fontFamily:'Inter_600SemiBold',fontSize:15},optionSub:{fontFamily:'Inter_400Regular',fontSize:12,marginTop:3},pill:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:5,paddingHorizontal:9,paddingVertical:5,borderRadius:99},pillText:{fontFamily:'Inter_700Bold',fontSize:10,letterSpacing:.3},card:{borderWidth:1,borderRadius:14,padding:15},});
