// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-concepts/Clarity.tsx": () => import("../components/mockups/brand-concepts/Clarity.tsx"),
  "./components/mockups/brand-concepts/Meridian.tsx": () => import("../components/mockups/brand-concepts/Meridian.tsx"),
  "./components/mockups/brand-concepts/Pulse.tsx": () => import("../components/mockups/brand-concepts/Pulse.tsx"),
  "./components/mockups/cop-guideline-builder/CoPGuidelineBuilder.tsx": () => import("../components/mockups/cop-guideline-builder/CoPGuidelineBuilder.tsx"),
  "./components/mockups/landing-pages/ClinicalAuthority.tsx": () => import("../components/mockups/landing-pages/ClinicalAuthority.tsx"),
  "./components/mockups/landing-pages/RegulatoryDoc.tsx": () => import("../components/mockups/landing-pages/RegulatoryDoc.tsx")
};
