// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cop-guideline-builder/CoPGuidelineBuilder.tsx": () => import("../components/mockups/cop-guideline-builder/CoPGuidelineBuilder.tsx")
};
